In [3]:
a= 12
b=20
c=(a**2+b**2)**0.5
print((a/c)*5)
print((b/c)*5)

def hipotenusa(a,b):
    c=(a**2+b**2)**0.5
    return c

e = (a/c)*5
f = (b/c)*5
print(hipotenusa(e,f))


2.5724787771376323
4.28746462856272
4.999999999999999


In [5]:
import numpy as np

v = np.array([[0.91, 0.65, 0.72, 0.10, 0.36], [0.01, 0.90, 0.44, 0.70, 0.08], [0.46, 0.69, 0.59, 0.34, 0.67], [0.31, 0.27, 0.97, 0.80, 0.39], [0.51, 0.93, 0.61, 0.35, 0.18], [0.11, 0.14, 0.93, 0.96, 0.25], [0.94, 0.17, 0.40, 0.16, 0.20], [0.44, 0.42, 0.98, 0.46, 0.31], [0.99, 0.22, 0.30, 0.06, 0.39], [0.49, 0.80, 0.43, 0.85, 0.85], [0.46, 0.14, 0.41, 0.64, 0.77]])

In [9]:
min(np.linalg.norm(v, axis=1))


1.0668176976409793

In [13]:
a = np.linalg.norm(v, axis=1)
for i in range(len(a)):
    print(f'{v[i]} -> {a[i]}')

[0.91 0.65 0.72 0.1  0.36] -> 1.3815209010362457
[0.01 0.9  0.44 0.7  0.08] -> 1.2247856955402443
[0.46 0.69 0.59 0.34 0.67] -> 1.265029643921438
[0.31 0.27 0.97 0.8  0.39] -> 1.379130160644745
[0.51 0.93 0.61 0.35 0.18] -> 1.2853015210447702
[0.11 0.14 0.93 0.96 0.25] -> 1.371386160058501
[0.94 0.17 0.4  0.16 0.2 ] -> 1.0668176976409793
[0.44 0.42 0.98 0.46 0.31] -> 1.2798828071350907
[0.99 0.22 0.3  0.06 0.39] -> 1.1288046775239726
[0.49 0.8  0.43 0.85 0.85] -> 1.5842979517754858
[0.46 0.14 0.41 0.64 0.77] -> 1.1839763511151733
